[build]
  command = "npm run build"
  publish = "build"

  [context.production.environment]
  VITE_YOUR_SERVICE_ID="service_9obblff"
  VITE_YOUR_TEMPLATE_ID="template_99p3p5q"
  VITE_YOUR_USER_ID="Ai3DC1MEwVueXhdli"